# Generated by Django 3.1.2 on 2020-10-25 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='Daily', max_length=30)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, help_text='Must have a country code', max_length=50, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('business_name', models.CharField(blank=True, max_length=100, null=True)),
                ('business_location', models.CharField(blank=True, max_length=50, null=True)),
                ('deliver', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=20, null=True)),
                ('bio', models.TextField(blank=True, help_text='Maximum 300 Words', max_length=400, null=True)),
                ('image', models.ImageField(default='product/default.png', upload_to='product')),
                ('cover_image', models.ImageField(default='cover/default.jpg', upload_to='cover')),
                ('is_seller', models.BooleanField(default=False)),
                ('plan', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=500)),
                ('rates', models.PositiveIntegerField(default=0)),
                ('approved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('actual_price', models.CharField(max_length=15)),
                ('previous_price', models.CharField(blank=True, max_length=15, null=True)),
                ('description', models.TextField(max_length=300)),
                ('image', models.ImageField(upload_to='product')),
                ('approved', models.BooleanField(default=False)),
                ('top_sale', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('product_type', models.CharField(choices=[('', 'Product or Service'), ('P', 'Product'), ('S', 'Service '), ('B', 'Both ')], max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('reviews', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.review')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
            ],
        ),
    ]
