# Generated by Django 3.1.2 on 2020-11-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201025_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(choices=[('Mwaiseni - FREE', 'Mwaiseni'), ('Kadyonko - K7/DAY', 'Kadyonko'), ('Mukolwe - K12/DAY', 'Mukolwe')], default='Mwaiseni - FREE', max_length=30),
        ),
    ]
