# Generated by Django 3.1.2 on 2020-11-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201127_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_type',
            field=models.CharField(choices=[('Food', 'Food'), ('Electronic', 'Electronic'), ('Clothes', 'Clothes'), ('Food', 'Food')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
