# Generated by Django 3.1.2 on 2020-11-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201123_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
