# Generated by Django 3.1.2 on 2020-11-22 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201123_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(choices=[('Mwaiseni - FREE', 'Mwaiseni'), ('Kadyonko - K2/DAY', 'Kadyonko'), ('Mukolwe - K15/Month', 'Mukolwe')], default='Mwaiseni - FREE', max_length=50),
        ),
    ]
