# Generated by Django 3.1.2 on 2020-11-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201127_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_type',
            field=models.CharField(choices=[('Food', 'Food'), ('Electronic', 'Electronic'), ('Home Appreance', 'Home Appreance'), ('Clothing', 'Clothing'), ('Shoes', 'Shoes'), ('Finance', 'Finance')], max_length=50),
        ),
    ]
