# Generated by Django 3.1.2 on 2020-11-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201123_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('', 'Product or Service'), ('Product', 'Product'), ('Service', 'Service '), ('Both', 'Both ')], max_length=20),
        ),
    ]
